spring:
  # redis配置
  redis:
      database: 1         # Redis数据库索引（默认为0）
      host: 127.0.0.1   # Redis服务器连接端口
      port: 6379
      password:
      timeout: 0           # 连接超时时间（毫秒）
      pool:
          max-active: 1024  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 20  # 连接池中的最大空闲连接
          min-idle: 0  # 连接池中的最小空闲连接
